name: movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_riverpod: ^1.0.4
  flutter_zoom_drawer: ^3.0.3
  fpdart: ^0.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  shimmer: ^2.0.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
